openapi: 3.0.3
info:
  title: Pacman API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /pacman/start:
    post:
      summary: Inicia partida
      responses:
        "200":
          description: OK
